name: Upload Prowler HTML Report

on:
  schedule:
    - cron: "0 9 * * 1-5"  # Trigger daily at 9 AM
    - cron: "0 9 * * 6"    # Trigger weekly on Saturday at 9 AM

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        run: |
          echo ${{ secrets.AWS_ACCESS_KEY_ID }} >> ~/.aws/credentials
          echo ${{ secrets.AWS_SECRET_ACCESS_KEY }} >> ~/.aws/credentials
          echo "[default]" >> ~/.aws/config
          echo "region=${{ secrets.AWS_DEFAULT_REGION }}" >> ~/.aws/config

      - name: Run Prowler and generate HTML report
        run: |
          docker run --rm -v $PWD:/prowler-report aquasec/prowler:latest -R -B html
          mv prowler-report.html prowler-report-${{ github.sha }}.html

      - name: Install AWS CLI
        run: |
          sudo apt-get install -y awscli

      - name: Upload HTML report to S3 bucket
        run: |
          aws s3 cp prowler-report-${{ github.sha }}.html s3://<bucket_name>/<path_in_bucket>/
